# Generated by Django 5.0.4 on 2024-04-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_cat_toys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='cat',
            name='description',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
