# Generated by Django 5.0.4 on 2024-04-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_cat_breed_alter_cat_description_alter_cat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
